export const FETCH_JWT_SUCCESS = 'FETCH_JWT_SUCCESS';
export const FETCH_JWT_FAILURE = 'FETCH_JWT_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REFRESH_JWT_SUCCESS = 'REFRESH_JWT_SUCCESS';
export const REFRESH_JWT_FAILURE = 'REFRESH_JWT_FAILURE';
export const VERIFY_JWT_SUCCESS = 'VERIFY_JWT_SUCCESS';
export const VERIFY_JWT_FAILURE = 'VERIFY_JWT_FAILURE';